"use client";
import {useEffect,useRef} from "react";
import * as THREE from "three";
import {GLTFLoader} from "three/examples/jsm/loaders/GLTFLoader.js";
import {OrbitControls} from "three/examples/jsm/controls/OrbitControls.js";
export default function ThreeViewer({animation,accent}:{animation:string;accent:string}){
 const mountRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{const mount=mountRef.current;if(!mount)return;const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(34,1,.01,100);camera.position.set(2.5,1.9,4.5);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;mount.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=2.2;controls.maxDistance=8;controls.target.set(0,1.05,0);scene.add(new THREE.HemisphereLight(0xdbeeff,0x11152a,2.2));const key=new THREE.DirectionalLight(accent,5);key.position.set(3,4,4);scene.add(key);const rim=new THREE.DirectionalLight(0x4774ff,3);rim.position.set(-4,2,-3);scene.add(rim);const floor=new THREE.Mesh(new THREE.CircleGeometry(2.4,64),new THREE.MeshStandardMaterial({color:0x080d1d,roughness:.85,metalness:.1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.02;scene.add(floor);let mixer:THREE.AnimationMixer|undefined;let disposed=false;new GLTFLoader().load("/models/rigged-simple.glb",gltf=>{if(disposed)return;const model=gltf.scene;const box=new THREE.Box3().setFromObject(model);const size=box.getSize(new THREE.Vector3());const center=box.getCenter(new THREE.Vector3());const scale=2.35/Math.max(size.y,.01);model.scale.setScalar(scale);model.position.set(-center.x*scale,-box.min.y*scale,-center.z*scale);scene.add(model);if(gltf.animations.length){mixer=new THREE.AnimationMixer(model);mixer.clipAction(gltf.animations[0]).play()}});const clock=new THREE.Clock();let frame=0;const render=()=>{frame=requestAnimationFrame(render);const d=clock.getDelta();mixer?.update(d*(animation==="RUN"?1.65:animation==="WALK"?.8:.45));controls.update();renderer.render(scene,camera)};const resize=()=>{const w=mount.clientWidth,h=mount.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/Math.max(h,1);camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(mount);resize();render();return()=>{disposed=true;observer.disconnect();cancelAnimationFrame(frame);controls.dispose();mixer?.stopAllAction();scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry?.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m?.dispose())}});renderer.dispose();renderer.domElement.remove()}},[animation,accent]);
 return <div className="three-viewer" ref={mountRef}><span className="viewer-help">ARRASTE PARA GIRAR // SCROLL PARA ZOOM</span><span className="viewer-credit">RIG TEST: KHRONOS/CESIUM · CC BY 4.0</span></div>
}
